Drop a slightly outdated type def for boolean type
This cases compilation errors with gcc 15 with the following error
message:

c-blosc/blosc/shuffle.c:26:15: error: 'bool' cannot be defined via 'typedef'
      | typedef _Bool bool;
      |               ^~~~
c-blosc/blosc/shuffle.c:26:15: note: 'bool' is a keyword with '-std=c23' onwards

See https://gcc.gnu.org/gcc-15/porting_to.html for details

I've choosen to remove the typedef as it seems to be unused in this
file.