CMake: Fix PThread Flag
On recent manylinux builds for ppc64le, I realized problems with
```
undefined reference to `pthread_atfork'
```

at linktime.

The reason for that is likely an outdated CMake flag that would
request the right pthread flags.

Old:
`CMAKE_THREAD_PREFER_PTHREAD` ([docs](https://cmake.org/cmake/help/v3.2/module/FindThreads.html))

New:
`THREADS_PREFER_PTHREAD_FLAG` ([docs](https://cmake.org/cmake/help/latest/module/FindThreads.html))